# Generated by Django 4.2.5 on 2023-11-04 03:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentimentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentimento",
                    models.CharField(
                        choices=[
                            ("insatisfeito", 0),
                            ("irritado", 1),
                            ("triste", 2),
                            ("chateado", 3),
                            ("tranquilo", 4),
                            ("alegre", 5),
                            ("feliz", 6),
                            ("satisfeito", 7),
                        ],
                        default="tranquilo",
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Relato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relato", models.TextField()),
                (
                    "estadoEmocionalNoRelato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relatos.sentimentos",
                    ),
                ),
                (
                    "usuarioRelator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relato_usuario",
                        to="pessoas.usuario",
                    ),
                ),
                (
                    "usuariosRelatados",
                    models.ManyToManyField(null=True, to="pessoas.usuario"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadoEmocional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criadoEm",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "sentimentoDeHoje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relatos.sentimentos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EscalaEmocional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(default="tranquilo", max_length=150)),
                ("sentimentos", models.ManyToManyField(to="relatos.sentimentos")),
            ],
        ),
    ]
