# Generated by Django 4.2.5 on 2023-11-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relatos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentimentos",
            name="sentimento",
            field=models.CharField(
                choices=[
                    (0, "insatisfeito"),
                    (1, "irritado"),
                    (2, "triste"),
                    (3, "chateado"),
                    (4, "tranquilo"),
                    (5, "alegre"),
                    (6, "feliz"),
                    (7, "satisfeito"),
                ],
                default="tranquilo",
                max_length=12,
            ),
        ),
    ]
